# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WW1x6N2ZuGPyf+68te2EGECOmcCoKMxAH1/2ZTGAG1FTH/90P1Ake949VIJeXR2SfD5SOMAlmoiUN6RyWXtu3WV/WbrLwWbCejBRk9+2W0LFWbBkIh8qiX009b7IdzKrui1eyUsL5klkSja+h84iKftl8efn+mVWmnEzzvfeTnbJ+V+f4VidetAFC9aJg0tPl0tbYkHPMsTxwpEgAz7VYMM27xk1lgMoXtnYPGsiA7sUbSJw9dI3h4l418enVwIoJHqHd4iOQ4yDQ9hgrMWmt1E1bNJyvNjKObDJOeRkX9be6tTz2tj1W4UL6eLhWKDfB/XzIPmY+Vuf+KNe4+dOq8YfIj9+g1LdC3bsC8pqFpHlhxkk5PMc+w5R9fsA//ZiMORNHnf7R77XnGobgFw9LRP0Ohv/qAbVc9LRBbEBx18g3hTVstlE5kNWQ0yGCruFk8wdyEw+0t9QPr62+2/zB4rvnELDdhJ56zg4+9yGpl1I22dU79gOX9+jbjkxFcEDltw0Eq1lQVE8rtXXFL6Qr+REL752HDB2HcF/eeuuWp+9+ZXydxiv8bXaVs21/9SC0aS01ieqDp76rSo+jPXi2j7fIm2mbbO2iiRjaLLQw/3PJsBSWmLN2JRB7RSS2jBOxWVWpWEciYEzB0mIlxKkgnechD2hs5qgi+hYKWyVSV0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
