travis:
  secure:
    BINSTAR_TOKEN: WW1x6N2ZuGPyf+68te2EGECOmcCoKMxAH1/2ZTGAG1FTH/90P1Ake949VIJeXR2SfD5SOMAlmoiUN6RyWXtu3WV/WbrLwWbCejBRk9+2W0LFWbBkIh8qiX009b7IdzKrui1eyUsL5klkSja+h84iKftl8efn+mVWmnEzzvfeTnbJ+V+f4VidetAFC9aJg0tPl0tbYkHPMsTxwpEgAz7VYMM27xk1lgMoXtnYPGsiA7sUbSJw9dI3h4l418enVwIoJHqHd4iOQ4yDQ9hgrMWmt1E1bNJyvNjKObDJOeRkX9be6tTz2tj1W4UL6eLhWKDfB/XzIPmY+Vuf+KNe4+dOq8YfIj9+g1LdC3bsC8pqFpHlhxkk5PMc+w5R9fsA//ZiMORNHnf7R77XnGobgFw9LRP0Ohv/qAbVc9LRBbEBx18g3hTVstlE5kNWQ0yGCruFk8wdyEw+0t9QPr62+2/zB4rvnELDdhJ56zg4+9yGpl1I22dU79gOX9+jbjkxFcEDltw0Eq1lQVE8rtXXFL6Qr+REL752HDB2HcF/eeuuWp+9+ZXydxiv8bXaVs21/9SC0aS01ieqDp76rSo+jPXi2j7fIm2mbbO2iiRjaLLQw/3PJsBSWmLN2JRB7RSS2jBOxWVWpWEciYEzB0mIlxKkgnechD2hs5qgi+hYKWyVSV0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
